# Generated by Django 5.2.8 on 2025-12-02 08:50

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowerlist',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='borrowerlist',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2025, 12, 16, 8, 50, 7, 921844, tzinfo=datetime.timezone.utc)),
        ),
    ]
