# Generated by Django 5.2.8 on 2025-12-03 07:25
from django.db import migrations

def create_librarian_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    group, created = Group.objects.get_or_create(name='Librarian')

    try: 
        permission_borrow_book = Permission.objects.get(codename='borrowBook')
        group.permissions.add(permission_borrow_book)
    
    except Permission.DoesNotExist:
        pass

    try:
        permission_return_book = Permission.objects.get(codename='returnBook')
        group.permissions.add(permission_return_book)

    except Permission.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0003_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_librarian_group),
    ]
