# Generated by Django 5.2.8 on 2025-12-03 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20251203_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowerlist',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['member_number']},
        ),
    ]
