# Generated by Django 5.2.8 on 2025-12-03 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_alter_borrowerlist_options_alter_member_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrowerlist',
            options={'ordering': ['due_date'], 'permissions': [('borrowBook', 'Can borrow a book'), ('returnBook', 'Can return a book')]},
        ),
    ]
